"""empty message

Revision ID: 07a5f17d3cc1
Revises: 40d15467b958
Create Date: 2022-08-12 21:09:23.917817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a5f17d3cc1'
down_revision = '40d15467b958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(), nullable=True))
    op.drop_column('artist', 'websitelink')
    op.add_column('venue', sa.Column('seeking_talent', sa.String(length=120), nullable=False))
    op.add_column('venue', sa.Column('website_link', sa.String(), nullable=True))
    op.drop_column('venue', 'seeking_venue')
    op.drop_column('venue', 'websitelink')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('websitelink', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('seeking_venue', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'seeking_talent')
    op.add_column('artist', sa.Column('websitelink', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
